package com.kavi.kavimart.controller;

import com.google.gson.JsonObject;import com.kavi.kavimart.dto.*;import com.kavi.kavimart.model.*;import com.kavi.kavimart.service.*;import com.kavi.kavimart.util.*;import javax.servlet.ServletException;import javax.servlet.http.*;import javax.sql.DataSource;import java.io.IOException;import java.math.BigDecimal;import java.sql.Connection;import java.util.*;
/** Versioned JSON endpoints for health, catalog, cart, orders, and reviews. */
public class ApiServlet extends BaseServlet {
 protected void service(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{try{String path=req.getPathInfo()==null?"/":req.getPathInfo();String method=req.getMethod();if(path.equals("/health")&&"GET".equals(method)){health(res);return;}if(path.startsWith("/products")&&"GET".equals(method)){products(req,res,path);return;}if(path.startsWith("/cart")){cart(req,res,path,method);return;}if(path.startsWith("/orders")){orders(req,res,path,method);return;}if(path.startsWith("/seller/orders")){sellerOrders(req,res,path,method);return;}if(path.startsWith("/reviews")){reviews(req,res,method);return;}JsonUtil.error(res,404,"NOT_FOUND","API route not found.",null);}catch(Throwable t){error(req,res,t);}}
 private void health(HttpServletResponse res)throws IOException{DataSource ds=service(getServletContext(),SessionKeys.DATA_SOURCE,DataSource.class);try(Connection c=ds.getConnection()){if(!c.isValid(2))throw new IllegalStateException("Database unavailable");JsonUtil.success(res,200,Map.of("status","UP","db","UP"));}catch(Exception e){JsonUtil.error(res,500,"DATABASE_UNAVAILABLE","Database is unavailable.",null);}}
 private void products(HttpServletRequest req,HttpServletResponse res,String path)throws IOException,ServletException{ProductService service=service(getServletContext(),SessionKeys.PRODUCT_SERVICE,ProductService.class);if(path.matches("/products/\\d+")){long id=Long.parseLong(path.substring(path.lastIndexOf('/')+1));JsonUtil.success(res,200,service.get(id));return;}ProductQuery query=new ProductQuery(req.getParameter("q"),req.getParameter("category"),req.getParameter("sort"),intParam(req,"page",1),intParam(req,"pageSize",12));JsonUtil.success(res,200,service.search(query));}
 private void cart(HttpServletRequest req,HttpServletResponse res,String path,String method)throws IOException,ServletException{UserResponseDTO u=user(req);CartService c=service(getServletContext(),SessionKeys.CART_SERVICE,CartService.class);if("GET".equals(method)){cartResponse(res,c,u.getId());return;}JsonObject body=body(req);if("POST".equals(method)){c.add(u.getId(),number(body,"productId"),intValue(body,"quantity",1));res.setHeader("Location",req.getRequestURI());cartResponse(res,c,u.getId());return;}long productId=path.matches("/cart/\\d+")?Long.parseLong(path.substring(path.lastIndexOf('/')+1)):number(body,"productId");if("PUT".equals(method)){c.update(u.getId(),productId,intValue(body,"quantity",0));cartResponse(res,c,u.getId());return;}if("DELETE".equals(method)){c.remove(u.getId(),productId);cartResponse(res,c,u.getId());return;}JsonUtil.error(res,405,"METHOD_NOT_ALLOWED","Method not allowed.",null);}
 private void cartResponse(HttpServletResponse res,CartService c,long id)throws IOException{JsonUtil.success(res,200,Map.of("items",c.getItems(id),"total",c.total(id)));}
 private void orders(HttpServletRequest req,HttpServletResponse res,String path,String method)throws IOException,ServletException{UserResponseDTO u=user(req);OrderService o=service(getServletContext(),SessionKeys.ORDER_SERVICE,OrderService.class);if("GET".equals(method)){JsonUtil.success(res,200,o.buyerOrders(u.getId()));return;}if("POST".equals(method)){JsonUtil.success(res,201,o.placeOrder(u.getId()));return;}if("PUT".equals(method)&&path.matches("/orders/\\d+/cancel")){long id=Long.parseLong(path.split("/")[2]);o.cancel(u.getId(),id);JsonUtil.success(res,200,Map.of("status","CANCELLED"));return;}JsonUtil.error(res,405,"METHOD_NOT_ALLOWED","Method not allowed.",null);}
 private void sellerOrders(HttpServletRequest req,HttpServletResponse res,String path,String method)throws IOException,ServletException{UserResponseDTO u=user(req);OrderService o=service(getServletContext(),SessionKeys.ORDER_SERVICE,OrderService.class);if("GET".equals(method)){JsonUtil.success(res,200,Map.of("orders",o.sellerOrders(u.getId()),"stats",o.sellerStats(u.getId())));return;}if("PUT".equals(method)){JsonObject b=body(req);long id=Long.parseLong(path.substring(path.lastIndexOf('/')+1));o.updateSellerStatus(u.getId(),id,stringValue(b,"status"));JsonUtil.success(res,200,Map.of("status","updated"));return;}JsonUtil.error(res,405,"METHOD_NOT_ALLOWED","Method not allowed.",null);}
 private void reviews(HttpServletRequest req,HttpServletResponse res,String method)throws IOException,ServletException{ReviewService reviews=service(getServletContext(),SessionKeys.REVIEW_SERVICE,ReviewService.class);if("GET".equals(method)){long id=longParam(req,"productId");JsonUtil.success(res,200,Map.of("items",reviews.list(id),"averageRating",reviews.average(id)));return;}if("POST".equals(method)){UserResponseDTO u=user(req);JsonObject b=body(req);Review result=reviews.create(u.getId(),number(b,"productId"),intValue(b,"rating",0),stringValue(b,"comment"));JsonUtil.success(res,201,result);return;}JsonUtil.error(res,405,"METHOD_NOT_ALLOWED","Method not allowed.",null);}
 private JsonObject body(HttpServletRequest req)throws IOException{try{return JsonUtil.gson().fromJson(req.getReader(),JsonObject.class);}catch(RuntimeException e){throw new com.kavi.kavimart.exception.ValidationException(Map.of("body","Send a valid JSON object."));}}
 private long number(JsonObject b,String key){try{return b.get(key).getAsLong();}catch(Exception e){throw new com.kavi.kavimart.exception.ValidationException(Map.of(key,"Enter a valid number."));}}
 private int intValue(JsonObject b,String key,int fallback){try{return b.has(key)?b.get(key).getAsInt():fallback;}catch(Exception e){throw new com.kavi.kavimart.exception.ValidationException(Map.of(key,"Enter a valid whole number."));}}
 private String stringValue(JsonObject b,String key){try{return b.has(key)?b.get(key).getAsString():null;}catch(Exception e){throw new com.kavi.kavimart.exception.ValidationException(Map.of(key,"Enter valid text."));}}
}
