package com.kavi.kavimart.service;

import com.kavi.kavimart.dao.CartDao;import com.kavi.kavimart.dao.ProductDao;import com.kavi.kavimart.exception.ConflictException;import com.kavi.kavimart.exception.ResourceNotFoundException;import com.kavi.kavimart.model.*;import com.kavi.kavimart.util.ValidationUtil;import java.math.BigDecimal;import java.util.*;
/** Buyer cart rules including stock-limited quantities. */
public class CartService {
 private final CartDao carts;private final ProductDao products;
 /** Create the service with DAO interfaces. */ public CartService(CartDao carts,ProductDao products){this.carts=carts;this.products=products;}
 /** Return a validated buyer cart. */ public List<CartItem> getItems(long userId){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(userId>0,"userId","A buyer is required.",e);ValidationUtil.throwIfAny(e);return carts.findByUser(userId);}
 /** Add an available product without exceeding stock. */ public void add(long userId,long productId,int quantity){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(userId>0,"userId","A buyer is required.",e);ValidationUtil.require(productId>0,"productId","A valid product is required.",e);ValidationUtil.require(quantity>0&&quantity<=99,"quantity","Quantity must be between 1 and 99.",e);ValidationUtil.throwIfAny(e);Product p=products.findById(productId).orElseThrow(()->new ResourceNotFoundException("Product not found."));int current=carts.findByUser(userId).stream().filter(i->i.getProduct().getId()==productId).mapToInt(CartItem::getQuantity).sum();if(current+quantity>p.getStockQty())throw new ConflictException("Requested quantity exceeds available stock.");carts.add(userId,productId,quantity);}
 /** Set quantity for an item already in the cart. */ public void update(long userId,long productId,int quantity){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(userId>0,"userId","A buyer is required.",e);ValidationUtil.require(productId>0,"productId","A valid product is required.",e);ValidationUtil.require(quantity>0&&quantity<=99,"quantity","Quantity must be between 1 and 99.",e);ValidationUtil.throwIfAny(e);Product p=products.findById(productId).orElseThrow(()->new ResourceNotFoundException("Product not found."));if(quantity>p.getStockQty())throw new ConflictException("Requested quantity exceeds available stock.");if(!carts.update(userId,productId,quantity))throw new ResourceNotFoundException("Cart item not found.");}
 /** Remove one cart line. */ public void remove(long userId,long productId){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(userId>0,"userId","A buyer is required.",e);ValidationUtil.require(productId>0,"productId","A valid product is required.",e);ValidationUtil.throwIfAny(e);if(!carts.remove(userId,productId))throw new ResourceNotFoundException("Cart item not found.");}
 /** Calculate the running cart total. */ public BigDecimal total(long userId){return getItems(userId).stream().map(CartItem::getLineTotal).reduce(BigDecimal.ZERO,BigDecimal::add);}
}
