package com.kavi.kavimart.service;

import com.kavi.kavimart.dao.OrderDao;import com.kavi.kavimart.dto.OrderSummaryDTO;import com.kavi.kavimart.exception.*;import com.kavi.kavimart.model.CartItem;import com.kavi.kavimart.service.payment.PaymentStrategy;import com.kavi.kavimart.util.ValidationUtil;import java.math.BigDecimal;import java.util.*;
/** Checkout, order status workflow, and role-specific order views. */
public class OrderService {
 private final OrderDao dao;private final CartService cartService;private final PaymentStrategy payment;
 /** Create the service with persistence, cart rules, and payment strategy. */ public OrderService(OrderDao dao,CartService carts,PaymentStrategy payment){this.dao=dao;this.cartService=carts;this.payment=payment;}
 /** Validate and place a cart through the atomic order persistence transaction. */ public OrderSummaryDTO placeOrder(long buyerId){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(buyerId>0,"buyerId","A buyer is required.",e);ValidationUtil.throwIfAny(e);List<CartItem> items=cartService.getItems(buyerId);if(items.isEmpty())throw new ConflictException("Your cart is empty.");BigDecimal amount=items.stream().map(CartItem::getLineTotal).reduce(BigDecimal.ZERO,BigDecimal::add);if(!payment.charge(buyerId,amount))throw new ConflictException("Payment was declined.");return dao.placeOrder(buyerId);}
 /** Return an order belonging to the buyer. */ public List<OrderSummaryDTO> buyerOrders(long buyerId){Map<String,String>e=ValidationUtil.errors();ValidationUtil.require(buyerId>0,"buyerId","A buyer is required.",e);ValidationUtil.throwIfAny(e);return dao.findByBuyer(buyerId);}
 /** Return seller orders with the seller's product lines. */ public List<OrderSummaryDTO> sellerOrders(long sellerId){Map<String,String>e=ValidationUtil.errors();ValidationUtil.require(sellerId>0,"sellerId","A seller is required.",e);ValidationUtil.throwIfAny(e);return dao.findBySeller(sellerId);}
 /** Return all orders for the administrator. */ public List<OrderSummaryDTO> allOrders(){return dao.findAll();}
 /** Advance an order through the seller workflow, rejecting invalid transitions. */ public void updateSellerStatus(long sellerId,long orderId,String next){Map<String,String>e=ValidationUtil.errors();ValidationUtil.require(sellerId>0,"sellerId","A seller is required.",e);ValidationUtil.require(orderId>0,"orderId","A valid order is required.",e);ValidationUtil.require(Set.of("CONFIRMED","SHIPPED","DELIVERED").contains(next),"status","Invalid order status.",e);ValidationUtil.throwIfAny(e);OrderSummaryDTO order=dao.findById(orderId).orElseThrow(()->new ResourceNotFoundException("Order not found."));if(order.getItems().stream().noneMatch(i->i.getSellerId()==sellerId))throw new ResourceNotFoundException("Order not found for this seller.");String expected=switch(order.getStatus()){case "PENDING"->"CONFIRMED";case "CONFIRMED"->"SHIPPED";case "SHIPPED"->"DELIVERED";default->"";};if(expected.isEmpty()||!expected.equals(next))throw new ConflictException("Order status can only move from "+order.getStatus()+" to "+expected+".");if(!dao.transitionSeller(orderId,sellerId,order.getStatus(),next))throw new ConflictException("Order status changed. Refresh and try again.");}
 /** Cancel a pending order for the buyer and restore its stock. */ public void cancel(long buyerId,long orderId){Map<String,String>e=ValidationUtil.errors();ValidationUtil.require(buyerId>0,"buyerId","A buyer is required.",e);ValidationUtil.require(orderId>0,"orderId","A valid order is required.",e);ValidationUtil.throwIfAny(e);if(!dao.cancelPending(orderId,buyerId))throw new ConflictException("Only your pending orders can be cancelled.");}
 /** Return seller order count and revenue. */ public Map<String,BigDecimal> sellerStats(long sellerId){Map<String,String>e=ValidationUtil.errors();ValidationUtil.require(sellerId>0,"sellerId","A seller is required.",e);ValidationUtil.throwIfAny(e);return dao.sellerStats(sellerId);}
}
