package com.kavi.kavimart.service;

import com.kavi.kavimart.dao.ProductDao;import com.kavi.kavimart.exception.ResourceNotFoundException;import com.kavi.kavimart.model.*;import com.kavi.kavimart.util.ValidationUtil;import java.util.*;
/** Catalog search and seller-owned listing business rules. */
public class ProductService {
 private final ProductDao dao;
 /** Create the service with a DAO interface. */ public ProductService(ProductDao dao){this.dao=dao;}
 /** Search listings with validated query and paging values. */ public PageResult<Product> search(ProductQuery q){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(q!=null,"query","A search query is required.",e);if(q!=null){ValidationUtil.require(q.getKeyword().length()<=100,"keyword","Search text is too long.",e);ValidationUtil.require(q.getCategory().length()<=50,"category","Category is too long.",e);ValidationUtil.require(q.getPage()>0&&q.getPageSize()>0&&q.getPageSize()<=48,"page","Page values are invalid.",e);}ValidationUtil.throwIfAny(e);return dao.search(q);}
 /** Find a public product by id. */ public Product get(long id){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(id>0,"id","A valid product is required.",e);ValidationUtil.throwIfAny(e);return dao.findById(id).orElseThrow(()->new ResourceNotFoundException("Product not found."));}
 /** List products owned by one seller. */ public List<Product> listSeller(long sellerId){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(sellerId>0,"sellerId","A valid seller is required.",e);ValidationUtil.throwIfAny(e);return dao.findBySeller(sellerId);}
 /** Validate and create a new listing for the seller. */ public Product create(long sellerId,Product p){validateProduct(sellerId,p,false);p.setSellerId(sellerId);return dao.create(p);}
 /** Validate and update only a seller-owned listing. */ public void update(long sellerId,Product p){validateProduct(sellerId,p,true);if(!dao.updateOwned(p,sellerId))throw new ResourceNotFoundException("Product not found or not owned by this seller.");}
 /** Delete only a seller-owned listing. */ public void delete(long sellerId,long productId){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(sellerId>0,"sellerId","Seller is required.",e);ValidationUtil.require(productId>0,"id","A valid product is required.",e);ValidationUtil.throwIfAny(e);if(!dao.deleteOwned(productId,sellerId))throw new ResourceNotFoundException("Product not found or not owned by this seller.");}
 /** Remove a listing as an administrator. */ public void adminDelete(long productId){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(productId>0,"id","A valid product is required.",e);ValidationUtil.throwIfAny(e);if(!dao.deleteAny(productId))throw new ResourceNotFoundException("Product not found.");}
 /** List every listing for admin moderation. */ public List<Product> listAll(){return dao.findAll();}
 private void validateProduct(long sellerId,Product p,boolean requireId){Map<String,String> e=ValidationUtil.errors();ValidationUtil.require(sellerId>0,"sellerId","A valid seller is required.",e);ValidationUtil.require(p!=null,"product","Product details are required.",e);if(p!=null){if(requireId)ValidationUtil.require(p.getId()>0,"id","A valid product is required.",e);ValidationUtil.require(p.getName()!=null&&!p.getName().trim().isEmpty()&&p.getName().length()<=200,"name","Name is required (200 characters maximum).",e);ValidationUtil.require(p.getDescription()==null||p.getDescription().length()<=5000,"description","Description is too long.",e);ValidationUtil.require(ValidationUtil.validPrice(p.getPrice()),"price","Price must be zero or greater with at most two decimal places.",e);ValidationUtil.require(p.getStockQty()>=0,"stock","Stock must be zero or greater.",e);ValidationUtil.require(p.getCategory()!=null&&!p.getCategory().isBlank()&&p.getCategory().length()<=50,"category","Choose a category.",e);ValidationUtil.require(p.getImageUrl()==null||p.getImageUrl().isBlank()||p.getImageUrl().length()<=500,"imageUrl","Image URL is too long.",e);}ValidationUtil.throwIfAny(e);}
}
