CREATE TABLE users (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL CHECK (role IN ('BUYER','SELLER','ADMIN')), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE products (id BIGINT AUTO_INCREMENT PRIMARY KEY, seller_id BIGINT NOT NULL, name VARCHAR(200) NOT NULL, description CLOB, price DECIMAL(10,2) NOT NULL CHECK (price >= 0), stock_qty INT NOT NULL CHECK (stock_qty >= 0), category VARCHAR(50) NOT NULL, image_url VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX idx_products_seller ON products(seller_id); CREATE INDEX idx_products_category ON products(category); CREATE INDEX idx_products_name ON products(name);
CREATE TABLE orders (id BIGINT AUTO_INCREMENT PRIMARY KEY, buyer_id BIGINT NOT NULL, status VARCHAR(20) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')), total_amount DECIMAL(10,2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users(id));
CREATE INDEX idx_orders_buyer ON orders(buyer_id); CREATE INDEX idx_orders_status ON orders(status);
CREATE TABLE order_items (id BIGINT AUTO_INCREMENT PRIMARY KEY, order_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity INT NOT NULL CHECK (quantity > 0), unit_price DECIMAL(10,2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id));
CREATE INDEX idx_order_items_order ON order_items(order_id); CREATE INDEX idx_order_items_product ON order_items(product_id);
CREATE TABLE cart_items (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity INT NOT NULL CHECK (quantity > 0), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT uq_cart_user_product UNIQUE(user_id, product_id), CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE INDEX idx_cart_user ON cart_items(user_id); CREATE INDEX idx_cart_product ON cart_items(product_id);
