package com.kavi.kavimart.dao.jdbc;

import com.kavi.kavimart.dao.CartDao;import com.kavi.kavimart.model.*;import javax.sql.DataSource;import java.sql.*;import java.util.*;import org.slf4j.Logger;import org.slf4j.LoggerFactory;
/** JDBC implementation of buyer cart persistence. */
public class JdbcCartDao implements CartDao {
 private static final Logger LOG=LoggerFactory.getLogger(JdbcCartDao.class);private final DataSource ds;
 /** Create cart persistence with a pooled data source. */ public JdbcCartDao(DataSource ds){this.ds=ds;}
 /** {@inheritDoc} */ public List<CartItem> findByUser(long id){String sql="SELECT c.id,c.user_id,c.quantity,p.id AS product_id,p.seller_id,p.name,p.description,p.price,p.stock_qty,p.category,p.image_url,p.created_at,u.name AS seller_name FROM cart_items c JOIN products p ON p.id=c.product_id JOIN users u ON u.id=p.seller_id WHERE c.user_id=? ORDER BY c.created_at";List<CartItem> out=new ArrayList<>();try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,id);try(ResultSet r=p.executeQuery()){while(r.next()){Product product=new Product(r.getLong("product_id"),r.getLong("seller_id"),r.getString("seller_name"),r.getString("name"),r.getString("description"),r.getBigDecimal("price"),r.getInt("stock_qty"),r.getString("category"),r.getString("image_url"),r.getTimestamp("created_at").toLocalDateTime());out.add(new CartItem(r.getLong("id"),r.getLong("user_id"),product,r.getInt("quantity")));}}return out;}catch(SQLException e){throw fail("read cart",e);}}
 /** {@inheritDoc} */ public void add(long user,long product,int qty){try(Connection c=ds.getConnection()){String update="UPDATE cart_items SET quantity=quantity+? WHERE user_id=? AND product_id=?";try(PreparedStatement p=c.prepareStatement(update)){p.setInt(1,qty);p.setLong(2,user);p.setLong(3,product);if(p.executeUpdate()>0)return;}try(PreparedStatement p=c.prepareStatement("INSERT INTO cart_items(user_id,product_id,quantity) VALUES(?,?,?)")){p.setLong(1,user);p.setLong(2,product);p.setInt(3,qty);p.executeUpdate();}}catch(SQLException e){throw fail("add cart item",e);}}
 /** {@inheritDoc} */ public boolean update(long user,long product,int qty){try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement("UPDATE cart_items SET quantity=? WHERE user_id=? AND product_id=?")){p.setInt(1,qty);p.setLong(2,user);p.setLong(3,product);return p.executeUpdate()>0;}catch(SQLException e){throw fail("update cart item",e);}}
 /** {@inheritDoc} */ public boolean remove(long user,long product){try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM cart_items WHERE user_id=? AND product_id=?")){p.setLong(1,user);p.setLong(2,product);return p.executeUpdate()>0;}catch(SQLException e){throw fail("remove cart item",e);}}
 /** {@inheritDoc} */ public void clear(long user){try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM cart_items WHERE user_id=?")){p.setLong(1,user);p.executeUpdate();}catch(SQLException e){throw fail("clear cart",e);}}
 private RuntimeException fail(String action,SQLException e){LOG.error("Database operation failed: {}",action,e);return new IllegalStateException("Database operation failed.",e);}
}
